version: '3'
services:

    bot:
        build:
            context: .
        env_file:
            - .env
        environment:
            - MONGODB_HOST=mongodb
            - MONGODB_PORT=27017
            - MONGODB_USER=${MONGODB_USER:-admin}
            - MONGODB_PASSWORD=${MONGODB_PASSWORD:-password}
            - MONGODB_DATABASE=${MONGODB_DATABASE:-bot}
            - NODE_ENV=production
        volumes:
            - ".:/app"
        command: npm run start
        depends_on:
            - mongodb
        restart: unless-stopped

    mongodb:
        image: mongo:latest
        ports:
            - "${MONGODB_PORT:-27017}:27017"
        volumes:
            - mongodb_data:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER:-admin}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD:-password}

    mongo-express:
        image: mongo-express:latest
        ports:
            - "${MONGO_EXPRESS_PORT:-8081}:${MONGO_EXPRESS_PORT:-8081}"
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USER:-admin}
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD:-password}
            - ME_CONFIG_MONGODB_SERVER=${MONGODB_HOST:-mongodb}
            - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT:-27017}
            - ME_CONFIG_PORT=${MONGO_EXPRESS_PORT:-8081}
        depends_on:
            - mongodb
        restart: unless-stopped

volumes:
    mongodb_data:
