version: '3.8'
services:

    bot:
        build: .
        env_file:
            - .env
        volumes:
            - ".:/app"
            - "/app/node_modules"
        command: npm run dev # Override for development mode
        depends_on:
            - mongodb
        environment:
            - TELEGRAM_API_TOKEN=${TELEGRAM_API_TOKEN}
            - OPENAI_API_KEY=${OPENAI_API_KEY}
            - GPT_VERSION=${GPT_VERSION}
            - MONGODB_HOST=${MONGODB_HOST}
            - MONGODB_PORT=${MONGODB_PORT}
            - MONGODB_USER=${MONGODB_USER}
            - MONGODB_PASSWORD=${MONGODB_PASSWORD}
            - MONGODB_DATABASE=${MONGODB_DATABASE}
            - MONGO_EXPRESS_PORT=${MONGO_EXPRESS_PORT}
            - LOG_LEVEL=${LOG_LEVEL}
        restart: always
        networks:
            - mirror-network

    mongodb:
        image: mongo:latest
        ports:
            - "${MONGODB_PORT:-27420}:27420"
        volumes:
            - mirror_mongodb_data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER:-admin}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:-password}
            MONGO_INITDB_DATABASE: ${MONGODB_DATABASE:-mirror}
        restart: always
        networks:
            - mirror-network

    mongo-express:
        image: mongo-express:latest
        ports:
            - "${MONGO_EXPRESS_PORT:-8081}:8081"
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER:-admin}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD:-password}
            ME_CONFIG_MONGODB_SERVER: mongodb
        depends_on:
            - mongodb
        restart: always
        networks:
            - mirror-network

volumes:
    mirror_mongodb_data:
        name: "mirror_mongodb_data"

networks:
    mirror-network:
        name: "mirror_network"
        driver: bridge
