version: '3'
services:

    bot:
        build:
            context: .
        env_file:
            - .env
        volumes:
            - ".:/app"
        command: npm run dev
        depends_on:
            - mongodb

    mongodb:
        image: mongo:latest
        ports:
            - "${MONGODB_PORT}:${MONGODB_PORT}"
        volumes:
            - mongodb_data:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password

    mongo-express:
        image: mongo-express:latest
        ports:
            - "${MONGO_EXPRESS_PORT:-8081}:${MONGO_EXPRESS_PORT:-8081}"
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=password
            - ME_CONFIG_MONGODB_SERVER=${MONGODB_HOST}
            - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT}
            - ME_CONFIG_PORT=${MONGO_EXPRESS_PORT:-8081}
        depends_on:
            - mongodb

volumes:
    mongodb_data:
