version: '3'
services:

    bot:
        build:
            context: .
        env_file:
            - .env
        environment:
            - MONGODB_HOST=mongodb
            - MONGODB_PORT=27017
        volumes:
            - ".:/app"
        command: npm run dev
        depends_on:
            - mongodb

    mongodb:
        image: mongo:latest
        ports:
            - "${MONGODB_PORT:-27017}:27017"
        volumes:
            - mongodb_data:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password

    mongo-express:
        image: mongo-express:latest
        ports:
            - "8081:8081"
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=password
            - ME_CONFIG_MONGODB_SERVER=${MONGODB_HOST:-mongodb}
            - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT:-27017}
        depends_on:
            - mongodb

volumes:
    mongodb_data:
